# Master settings file for repository
# Will have a google_settings entry for google-as-template details


google_settings:
  # project_dir: 'enter_the_key_for_project_folder_here'
  project_dir: '1HWMeTZ_Mv2GA7Ldl7onAutpuYKyzrkn7'
  # project_name: 'Enter the name of your project here'
  project_name: 'GAS Test'
  # script_name: 'Enter the name of your script file here (will be created)'
  script_name: 'Apps Scripts'
  store_dir: '.credentials'  # From this line down, modifiable defaults
  credentials_file: 'credentials.json'
  credentials_store: 'credentials_store.json'
  scopes:  # If these are changed, repeat flow by rm'ing credentials_store.json
    - 'https://www.googleapis.com/auth/drive'
    - 'https://spreadsheets.google.com/feeds'
    - 'https://www.googleapis.com/auth/spreadsheets'
